version: '3'

services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./documents:/app/documents
  
  document-watcher:
    build:
      context: .
      dockerfile: Dockerfile
    command: python watcher_service.py
    env_file:
      - .env
    environment:
      
      - WATCH_DIRECTORY=/app/documents
      - API_ENDPOINT=http://rag-api:8000/upload
    volumes:
      - ./documents:/app/documents
    depends_on:
      - rag-api